-- V1: 초기 스키마
-- 스키마 소유권은 Flyway에 있으며, Hibernate는 ddl-auto=validate로 검증만 수행한다.
-- 열거형은 DB 고유 enum 타입 대신 varchar + check 제약으로 표현한다
-- (PostgreSQL/H2 양쪽에서 동일하게 동작하며, 값 추가 시 제약만 교체하면 된다).

create table users (
    id         bigint generated by default as identity,
    email      varchar(255) not null unique,
    password   varchar(255) not null,
    name       varchar(255) not null,
    age        integer,
    gender     varchar(255),
    job        varchar(255),
    location   varchar(255),
    role       varchar(255) not null,
    status     varchar(255) not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint ck_users_gender check (gender in ('FEMALE', 'MALE')),
    constraint ck_users_role check (role in ('ADMIN', 'USER')),
    constraint ck_users_status check (status in ('ACTIVE', 'PENDING', 'SUSPENDED'))
);

create table match_records (
    id           bigint generated by default as identity,
    requester_id bigint not null,
    partner_id   bigint not null,
    status       varchar(255) not null,
    score        double precision,
    version      bigint not null,
    created_at   timestamp(6) not null,
    primary key (id),
    constraint ck_match_records_status check (status in ('ACCEPTED', 'REJECTED', 'REQUESTED'))
);

create table qna (
    id          bigint generated by default as identity,
    user_id     bigint not null,
    title       varchar(255) not null,
    question    varchar(2000) not null,
    answer      varchar(2000),
    status      varchar(255) not null,
    created_at  timestamp(6) not null,
    answered_at timestamp(6),
    primary key (id),
    constraint ck_qna_status check (status in ('ANSWERED', 'WAITING'))
);

create table notifications (
    id             bigint generated by default as identity,
    target_user_id bigint,
    title          varchar(255) not null,
    message        varchar(2000) not null,
    created_at     timestamp(6) not null,
    primary key (id)
);
