-- V1: 초기 스키마 (Hibernate 생성 DDL을 실측 덤프하여 고정)
-- 스키마 소유권은 Flyway에 있으며, Hibernate는 ddl-auto=validate로 검증만 수행한다.

create table users (
    id         bigint generated by default as identity,
    email      varchar(255) not null unique,
    password   varchar(255) not null,
    name       varchar(255) not null,
    age        integer,
    gender     enum ('FEMALE', 'MALE'),
    job        varchar(255),
    location   varchar(255),
    role       enum ('ADMIN', 'USER') not null,
    status     enum ('ACTIVE', 'PENDING', 'SUSPENDED') not null,
    created_at timestamp(6) not null,
    primary key (id)
);

create table match_records (
    id           bigint generated by default as identity,
    requester_id bigint not null,
    partner_id   bigint not null,
    status       enum ('ACCEPTED', 'REJECTED', 'REQUESTED') not null,
    score        float(53),
    version      bigint not null,
    created_at   timestamp(6) not null,
    primary key (id)
);

create table qna (
    id          bigint generated by default as identity,
    user_id     bigint not null,
    title       varchar(255) not null,
    question    varchar(2000) not null,
    answer      varchar(2000),
    status      enum ('ANSWERED', 'WAITING') not null,
    created_at  timestamp(6) not null,
    answered_at timestamp(6),
    primary key (id)
);

create table notifications (
    id             bigint generated by default as identity,
    target_user_id bigint,
    title          varchar(255) not null,
    message        varchar(2000) not null,
    created_at     timestamp(6) not null,
    primary key (id)
);
