-- V3: 1:1 채팅 메시지 테이블 (대화방 = ACCEPTED 상태의 match_records.id)

create table chat_messages (
    id         bigint generated by default as identity,
    match_id   bigint not null,
    sender_id  bigint not null,
    content    varchar(500) not null,
    created_at timestamp(6) not null,
    primary key (id)
);

-- afterId 증분 조회(match_id = ? and id > ?) 최적화
create index idx_chat_messages_match_id_id on chat_messages (match_id, id);
